<a href="https://colab.research.google.com/github/egynzhu-personal/siop-python-seminar-2024/blob/main/05_activity.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Final Activity
## In this activity you will
- Train a machine learning model to predict turnover on IBM's dataset
- Evaluate its performance
## We will build on some skills leveraged throughout the course including:
1. Data manipulation in Pandas
2. Conditionals (if statements)
3. Machine Learning
4. OOP (Bonus)
5. Visualization (Bonus)

In [4]:
import pandas as pd

!wget attrition.csv https://github.com/egynzhu-personal/siop-python-seminar-2024/raw/main/data/WA_Fn-UseC_-HR-Employee-Attrition.csv

df = pd.read_csv('WA_Fn-UseC_-HR-Employee-Attrition.csv')
df.head()

--2024-04-17 18:46:31--  http://attrition.csv/
Resolving attrition.csv (attrition.csv)... failed: Name or service not known.
wget: unable to resolve host address ‘attrition.csv’
--2024-04-17 18:46:31--  https://github.com/egynzhu-personal/siop-python-seminar-2024/raw/main/data/WA_Fn-UseC_-HR-Employee-Attrition.csv
Resolving github.com (github.com)... 140.82.113.4
Connecting to github.com (github.com)|140.82.113.4|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/egynzhu-personal/siop-python-seminar-2024/main/data/WA_Fn-UseC_-HR-Employee-Attrition.csv [following]
--2024-04-17 18:46:31--  https://raw.githubusercontent.com/egynzhu-personal/siop-python-seminar-2024/main/data/WA_Fn-UseC_-HR-Employee-Attrition.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 227977 (223K) [text/plain]
Saving to: ‘WA_Fn-UseC_-HR-Employee-Attrition.csv.3’

WA_Fn-UseC_-HR-Empl 100%[===================>] 222.63K  --.-KB/s    in 0.03s

2024-04-17 18:46:31 (8.41 MB/s) - ‘WA_Fn-UseC_-HR-Employee-Attrition.csv.3’ saved [227977/227977]

FINISHED --2024-04-17 18:46:31--
Total wall clock time: 0.3s
Downloaded: 1 files, 223K in 0.03s (8.41 MB/s)

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,...,1,80,0,8,0,1,6,4,0,5
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2,...,4,80,1,10,3,3,10,7,1,7
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,1,4,...,2,80,0,7,3,3,0,0,0,0
3,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,1,5,...,3,80,0,8,3,3,8,7,3,0
4,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,7,...,4,80,1,6,3,3,2,2,2,2

## Recommended Libraries

In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import classification_report
from sklearn.preprocessing import OneHotEncoder

# Below are function docstrings to help guide you through the activity
- You may utilize them, tweak them, or code your own if you would like

## Remove Missing Data
- Include a conditional!
- If there is no missing data, then just return the dataframe

In [7]:
def remove_missing_rows(df):
    """
    Remove rows with missing values from the DataFrame.

    Parameters:
    df (DataFrame): Input DataFrame with potential missing values.

    Returns:
    DataFrame: DataFrame with missing rows removed.
    """
    pass

## Train test split

In [6]:
def train_test_split_data(df, target_col, test_size=0.2, random_state=42):
    """
    Split the data into training and test sets.

    Parameters:
    df (DataFrame): Input DataFrame.
    target_col (str): Name of the target column.
    test_size (float): Proportion of the dataset to include in the test split.
    random_state (int): Random state for reproducibility.

    Returns:
    tuple: (X_train, X_test, y_train, y_test)
    """
    pass

## One hot encoding of categorical features

In [ ]:
def one_hot_encode(df, columns_to_encode):
    """
    Perform one-hot encoding on specified columns in the DataFrame.

    Parameters:
    df (DataFrame): Input DataFrame.
    columns_to_encode (list): List of column names to encode.

    Returns:
    DataFrame: DataFrame with one-hot encoded columns.
    """
    pass

## Fit and Evaluate Model

In [5]:
def fit_evaluate_model(model, X_train, X_test, y_train, y_test):
    """
    Fit a given model and evaluate its performance.

    Parameters:
    model: Machine learning model instance.
    X_train (DataFrame): Training features.
    X_test (DataFrame): Test features.
    y_train (Series): Training target.
    y_test (Series): Test target.

    Returns:
    dict: Classification report.
    """
    pass

## Example Code Usage

In [ ]:

# Example usage:
# Load the dataset
# df = pd.read_csv('ibm_employee_attrition.csv')

# Remove missing rows
# df_clean = remove_missing_rows(df)

# Train-test split
# X_train, X_test, y_train, y_test = train_test_split_data(df_clean, 'Attrition')

# One-hot encode categorical columns
# categorical_cols = ['BusinessTravel', 'Department', 'EducationField', 'Gender', 'JobRole', 'MaritalStatus', 'Over18', 'OverTime']
# X_train_encoded = one_hot_encode(X_train, categorical_cols)
# X_test_encoded = one_hot_encode(X_test, categorical_cols)

# Instantiate DecisionTreeClassifier
# model = DecisionTreeClassifier(random_state=42)

# Fit and evaluate model
# report = fit_evaluate_model(model, X_train_encoded, X_test_encoded, y_train, y_test)
# print(report)

## Bonus!
- Create a class that:
1. removes missing rows
2. one hot encodes categorical cols

Recommended init:
- categorical columns

In [ ]:
# Example usage:
# data_preprocessor = DataPreprocessor(categorical_cols=['BusinessTravel', 'Department', 'EducationField', 'Gender', 'JobRole', 'MaritalStatus', 'Over18', 'OverTime'])
# df_clean = data_preprocessor.remove_missing_rows(df)
# df_encoded = data_preprocessor.one_hot_encode(df_clean)

# Bonus #2
1. Visualize Model Performance
- Recommended Approach: Use matplotlib to plot the classification report